name: clang-format
on: [push]
jobs:
  dry-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format
        run: |
          sudo apt install clang-format
      - name: Run clang-format
        run: |
          find . -regex '^\./src/.*\.\(cpp\|h\)$' -not -path './src/jsui/*' |
            xargs clang-format -i --dry-run --Werror
