
name: Test

on: [push]

env:
  PROJECT_NAME: Os251
  CMAKE_VERSION: 3.16.2
  NINJA_VERSION: 1.9.0
  BUILD_TYPE: Release
  CCACHE_VERSION: 3.7.7

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - if: ${{ runner.os=='Windows' }}
      name: See env variables
      run: | 
        echo ==============================================
        Get-Item Env:PATH
        echo ==============================================
        echo $Env:PATH
        echo ==============================================
        Get-Item Env:VSINSTALLDIR
        echo ==============================================
        echo $Env:VSINSTALLDIR

 